{% set name = "pyfor" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brycefrank/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 9ffe7714c539e7390e2169271f01d82fd1a8f9d2cc769c146b6bd409ae23dede
build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - gdal
    - geopandas
    - joblib
    - laxpy
    - laspy
    - lastools
    - libkml
    - matplotlib-base
    - numba
    - numpy
    - pandas
    - poppler
    - plyfile
    - python >=3.6
    - rasterio
    - scipy

test:
  imports:
    - pyfor

about:
  home: https://github.com/brycefrank/pyfor
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'LiDAR processing for forest inventories.'

  # The remaining entries in this section are optional, but recommended.
  description: |
    pyfor processes LiDAR and other point cloud data into useful metrics
    for forest inventory predictions.
  dev_url: https://github.com/brycefrank/pyfor

extra:
  recipe-maintainers:
    - brycefrank
